#!/bin/bash -l

# Set SCC project
#$ -P dietzelab

# Specify hard time limit for the job.
#   The job will be aborted if it runs longer than this time.

#$ -l h_rt=100:00:00
#$ -pe omp 4 -l mem_per_core=8G

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m ea

# Request buyin nodes
#$ -l buyin

# Merge stderr into the stdout file, to reduce clutter
#$ -j y
#$ -o fit_functional_groups_betareg.log

# Start 10 tasks (each will set its own j value)
#$ -t 6-40

cd /projectnb/talbot-lab-data/zrwerbin/temporal_forecast/

module load R/4.1.2
Rscript /projectnb2/talbot-lab-data/zrwerbin/temporal_forecast/analysis/workflows/b_functional_groups/01_fit_functional_groups.r $SGE_TASK_ID
